name: Helm Chart Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0 

      - name: Helm Lint
        run: |
          helm lint ./cosmocloud-deploy --set kubeconfig=/path/to/kubeconfig.yaml
          
      - name: Helm Template
        run: |
          helm template ./cosmocloud-deploy > template-output.yaml

      - name: Apply Templates
        run: |
          kubectl apply -f template-output.yaml
