name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/testapp-frontend:${{ github.sha }}
    
    - name: Build and Push Backend Image
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/testapp-backend:${{ github.sha }}
    
    - name: Build and Push Redis Image
      uses: docker/build-push-action@v2
      with:
        context: ./redis
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/testapp-redis:${{ github.sha }}
    
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.7.0'
    
    - name: Set up Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'
    
    - name: Configure Kubernetes credentials
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
        chmod 600 ~/.kube/config
    
    - name: Update Helm values with new image tags
      run: |
        sed -i 's|tag:.*|tag: ${{ github.sha }}|g' ./cosmocloud-deploy/values.yaml
    
    - name: Install Helm chart
      run: |
        helm install ${{ secrets.HELM_RELEASE_NAME }} ./cosmocloud-deploy --atomic --timeout 30s
    
    - name: Test deployment
      run: |
        kubectl get pods
        kubectl get services
