name: Helm Chart Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0 


      - name: Helm Lint
        run: |
          helm lint ./cosmocloud-deploy


      - name: Helm Template Validation
        run: |
          helm template test ./cosmocloud-deploy > output.yaml
          kubectl apply --dry-run=client -f output.yaml


      - name: Validate YAML Syntax
        uses: instrumenta/kubeval-action@v1.0.0
        with:
          files: output.yaml
