name: Helm Chart Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Set up yamllint
        run: |
          sudo apt-get update
          sudo apt-get install -y yamllint

      - name: Set up helm-unittest
        run: |
          helm plugin install https://github.com/quintush/helm-unittest

      - name: Helm Lint
        run: |
          helm lint ./cosmocloud-deploy

      - name: YAML Lint
        run: |
          yamllint ./cosmocloud-deploy

      - name: Helm Unit Tests
        run: |
          helm unittest ./cosmocloud-deploy

      - name: Helm Template Validation
        run: |
          helm template ./cosmocloud-deploy | kubeval --strict

      - name: Helm Dependency Update
        run: |
          helm dependency update ./cosmocloud-deploy

      - name: Helm Install Dry Run
        run: |
          helm install --dry-run --debug my-release ./cosmocloud-deploy
