name: Helm Chart Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: cosmocloud-deploy  # Set the checkout path explicitly

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0 

      - name: Helm Lint
        run: |
          helm lint . --set kubeconfig=/path/to/kubeconfig.yaml  # Lint directly from the `cosmocloud-deploy` folder
          
      - name: Helm Template
        run: |
          helm template . > template-output.yaml  # Use the current directory (cosmocloud-deploy)

      - name: Apply Templates
        run: |
          kubectl apply -f template-output.yaml
